# Generated by Django 3.2.6 on 2021-08-16 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('item_type', models.CharField(choices=[('Toy', 'Toy'), ('Clothes', 'Clothes'), ('Tool', 'Tool')], max_length=7)),
                ('condition', models.CharField(choices=[('Brand new', 'Brand new'), ('Used', 'Used'), ('Used with some issues', 'Used with some issues')], max_length=21)),
                ('type', models.CharField(choices=[('Search', 'Search'), ('Give-away', 'Give-away')], max_length=9)),
                ('image', models.ImageField(upload_to='items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
