# Generated by Django 3.2.6 on 2021-08-20 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('Brand new', 'Brand new'), ('Used', 'Used'), ('Used with some issues', 'Used with some issues')], max_length=21, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters allowed')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_type',
            field=models.CharField(choices=[('Toy', 'Toy'), ('Clothes', 'Clothes'), ('Tool', 'Tool')], max_length=7, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters allowed')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters allowed')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Search', 'Search'), ('Give-away', 'Give-away')], max_length=9, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters allowed')]),
        ),
    ]
