# Generated by Django 3.2.6 on 2021-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_content', '0003_auto_20210820_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('Brand new', 'Brand new'), ('Used', 'Used'), ('Used with some issues', 'Used with some issues')], max_length=21),
        ),
        migrations.AlterField(
            model_name='post',
            name='item_type',
            field=models.CharField(choices=[('Toy', 'Toy'), ('Clothes', 'Clothes'), ('Tool', 'Tool')], max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Search', 'Search'), ('Give-away', 'Give-away')], max_length=9),
        ),
    ]
